### PR TITLE
Vyperdatum 0.1.8 - Add extra regions

### PR DESCRIPTION
**Pull request by ericgyounkin**

### CODE REVIEW

**Comment by ericgyounkin** [comment]
I'll look into this a bit more tomorrow.  Only thing I see missing currently is a DatumData.set_custom_directory similar to set_vdatum_directory but for the custom path.

**Comment by GlenRice-NOAA** [comment]
Thanks.  My thought was to leave that alone (so just editing the config directly) until we had decided which path to use for incorporating multiple version of VDatum.

**Comment by ericgyounkin** [comment]
It's funny, I was sure that I added tif support as a viable option for region grids, but I didn't I guess.  I only added it as a discoverable grid type.  Not added in an operational sense.  I'll work on that.

**Comment by ericgyounkin** [comment]
I think this is probably fine.  it ensures that the return from get_transformation_pipeline will always have the grids with the correct file extensions.  It is annoying that the pipeline starts out all .gtx, but I don't think it hurts anything.

Your custom region lacks a tss, so I can't test everything.  But it appears to work otherwise.

**Pull request merged**
